[toolchain]
solana_version = "2.2.0"
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
amongsol_staking = "J1EHYJokNcbDGKYk3W8wkpmfAUogjD1NGq1jonPx2CnA"

[programs.localnet]
amongsol_staking = "J1EHYJokNcbDGKYk3W8wkpmfAUogjD1NGq1jonPx2CnA"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run lint --prefix frontend"

[hooks]
