[build]
buildCommand = "rustup install stable && cargo +stable build --release && mkdir -p bin && cp target/release/amongsol-backend bin/amongsol_backend"

[deploy]
startCommand = "./bin/amongsol_backend"
